// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sspbiviohnqbixhuhpfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcGJpdmlvaG5xYml4aHVocGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDE5NTksImV4cCI6MjA3MTYxNzk1OX0.FlzgCk7A9ONCDoGQ2fDsT6x8abxIe0DpnHIGM31XAzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});